QUERY TO RECOVERY DATA.... NO ORACLE LICENSE REQUIRED NO EXTERNAL MODULE... IS TESTED ON ORACLE STANDARD LICENSE

INSERT INTO SCHEMA_NOME.TABELLA_RECUPERATA_05122016_3 (
select * from SCHEMA_NOME.TABELLA_DA_RECUPARE as of timestamp to_timestamp('05-DEC-2016 21:18:00', 'DD-MON-YYYY HH24:MI:SS') );
COMMIT

SCHEMA_NOME.TABELLA_DA_RECUPARE is table to recovery
SCHEMA_NOME.TABELLA_RECUPERATA_05122016_3  is DESTINATION of table restored.
